package org.tradelib.events;

import org.tradelib.core.Bar;

/**
 * The event class generated by a data feed.
 */
public class BarEvent {
   public final Bar bar;
   public BarEvent(Bar b) {
      bar = b;
   }
}
